// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIZAhhGZpz3_rJM7Br7eaUTcbpIpPHWjg',
    appId: '1:399687369534:android:b1dbc8c855ae0ba0d2e26f',
    messagingSenderId: '399687369534',
    projectId: 'dash-clicker---codelabs-c8765',
    storageBucket: 'dash-clicker---codelabs-c8765.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCEmAjDgFTvWiFoOxbzY6_i84xO0avsMM',
    appId: '1:399687369534:ios:2dad28d64a9e984bd2e26f',
    messagingSenderId: '399687369534',
    projectId: 'dash-clicker---codelabs-c8765',
    storageBucket: 'dash-clicker---codelabs-c8765.appspot.com',
    iosClientId: '399687369534-ib3qkk927b1jqfoe4gn72bidb2oqmtuj.apps.googleusercontent.com',
    iosBundleId: 'br.afixcode.codelabs',
  );
}
